print("     /~\\")
print(r"    ( oo|")
print(r"    _\=/_")
print("   /  _  \\")
print(r"  //|/.\|\\")
print(r" ||  \ /  ||")
print(r"============")
print(r"|          |")
print(r"|          |")
print(r"|          |")